name: Production workflow

on:
  pull_request:
    branches:
      - main

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TEST"
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - run: sleep 5s
      - run: echo "DEPLOYMENT"
